<?php

namespace AppBundle\Repository;

/**
 * DescargaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescargaRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDirectas()
    {
        return $this->createQueryBuilder('d')
            ->where('d.directa = 1')
            ->andWhere('d.completada = 0')
            ->getQuery()
            ->getResult();
    }

    public function getManuales()
    {
        return $this->createQueryBuilder('d')
            ->where('d.directa = 0')
            ->andWhere('d.completada = 0')
            ->getQuery()
            ->getResult();
    }

    public function getPublicas($completada = 0)
    {
        $consulta = $this->createQueryBuilder('d')
            ->where('d.privada = 0');
        if ($completada == 0) {
            $consulta->andWhere('d.completada = 0');
        }
        if ($completada == 1) {
            $consulta->andWhere('d.completada = 1');
        }
        return $consulta->getQuery()->getResult();
    }
}
